apiVersion: v1
kind: Pod
metadata:
  name: my-red-po
  labels: 
    app: red 
  namespace: prob
spec:
  containers:
    - name: my-red-co
      image: longflew/ingress:REDPAGE
      ports:
        - containerPort: 80
      startupProbe:
        exec:
          command: ["cat >> file1"]
        failureThreshold: 5
        successThreshold: 1
        initialDelaySeconds: 3
      livenessProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 5
        successThreshold: 1
        initialDelaySeconds: 3
      readinessProbe:
        tcpSocket:
          port: 80
        failureThreshold: 5
        successThreshold: 1
        initialDelaySeconds: 3